-- =============================================================================
-- 00_roles_and_grants.sql
-- Workshop: Metadata-First Data Quality on Snowflake
-- Step  : 00-A — Security foundation
-- Run as: ACCOUNTADMIN (free trial default)
--
-- Principles applied:
--   CoC  – role names follow a consistent SCREAMING_SNAKE_CASE convention
--   DRY  – future grants mean new objects inherit rights automatically
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- ── Roles ────────────────────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS METADATA_STEWARD
    COMMENT = 'Owns and governs the QUALITY database and its metadata framework.';

CREATE ROLE IF NOT EXISTS DATA_ENGINEER
    COMMENT = 'Builds and maintains pipelines; has full access to QUALITY and CURATED.';

-- Grant roles upward so SYSADMIN (and ACCOUNTADMIN) can administer them
GRANT ROLE METADATA_STEWARD TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER    TO ROLE SYSADMIN;

-- ── Warehouse (if not already present) ───────────────────────────────────────
-- Free-trial accounts include COMPUTE_WH; use it or create a workshop WH.
CREATE WAREHOUSE IF NOT EXISTS WORKSHOP_WH
    WAREHOUSE_SIZE   = 'X-SMALL'
    AUTO_SUSPEND     = 60
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Shared workshop warehouse — auto-suspends after 60 s idle.';

GRANT USAGE, OPERATE ON WAREHOUSE WORKSHOP_WH TO ROLE METADATA_STEWARD;
GRANT USAGE, OPERATE ON WAREHOUSE WORKSHOP_WH TO ROLE DATA_ENGINEER;

-- ── Database-level grants (filled in after DBs are created in 01_*.sql) ──────
-- The grants below use "IF EXISTS" style by granting on the databases directly.
-- Run 01_databases_and_schemas.sql FIRST, then re-run this block if needed,
-- or simply run both files in order — they are idempotent.

-- QUALITY database
GRANT ALL PRIVILEGES ON DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON DATABASE QUALITY TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON ALL SCHEMAS     IN DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON ALL SCHEMAS     IN DATABASE QUALITY TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON ALL TABLES      IN DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON ALL TABLES      IN DATABASE QUALITY TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON ALL VIEWS       IN DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON ALL VIEWS       IN DATABASE QUALITY TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON ALL PROCEDURES  IN DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON ALL PROCEDURES  IN DATABASE QUALITY TO ROLE DATA_ENGINEER;

-- Future grants — new objects created in QUALITY automatically inherit rights
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS    IN DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS    IN DATABASE QUALITY TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON FUTURE TABLES     IN DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON FUTURE TABLES     IN DATABASE QUALITY TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON FUTURE VIEWS      IN DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON FUTURE VIEWS      IN DATABASE QUALITY TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE QUALITY TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE QUALITY TO ROLE DATA_ENGINEER;

-- CURATED database (source-system curated data)
GRANT ALL PRIVILEGES ON DATABASE CURATED TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON DATABASE CURATED TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON ALL SCHEMAS    IN DATABASE CURATED TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON ALL SCHEMAS    IN DATABASE CURATED TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON ALL TABLES     IN DATABASE CURATED TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON ALL TABLES     IN DATABASE CURATED TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE CURATED TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE CURATED TO ROLE DATA_ENGINEER;

GRANT ALL PRIVILEGES ON FUTURE TABLES  IN DATABASE CURATED TO ROLE METADATA_STEWARD;
GRANT ALL PRIVILEGES ON FUTURE TABLES  IN DATABASE CURATED TO ROLE DATA_ENGINEER;

-- ── Verify ────────────────────────────────────────────────────────────────────
SHOW ROLES LIKE 'METADATA_STEWARD';
SHOW ROLES LIKE 'DATA_ENGINEER';
